-- Seed 200 curated artists for LP crawler
INSERT INTO curated_artists (artist_name, priority) VALUES
-- Rock Classics
('Fleetwood Mac', 1),
('Bruce Springsteen', 1),
('U2', 1),
('The Doors', 1),
('R.E.M.', 1),
('Prince', 1),
('Madonna', 1),
('Michael Jackson', 1),
('Whitney Houston', 1),
('Stevie Wonder', 1),
('Marvin Gaye', 1),
('Aretha Franklin', 1),
('James Brown', 1),
('Elvis Presley', 1),
('Chuck Berry', 1),
('The Beach Boys', 1),
('Simon & Garfunkel', 1),
('Bob Marley & The Wailers', 1),
('Ramones', 1),
('The Clash', 1),
('Sex Pistols', 1),
('Talking Heads', 1),
('Blondie', 1),
('Sonic Youth', 1),
('Pixies', 1),
('The Cure', 1),
('Depeche Mode', 1),
('New Order', 1),
('The Stone Roses', 1),
('Oasis', 1),
('Blur', 1),
('Pulp', 1),
('Suede', 1),
('Arctic Monkeys', 1),
('The Strokes', 1),
('The White Stripes', 1),
('Queens of the Stone Age', 1),
('Foo Fighters', 1),
('Red Hot Chili Peppers', 1),
('Pearl Jam', 1),
('Soundgarden', 1),
('Alice in Chains', 1),
('The Smashing Pumpkins', 1),
('Jane''s Addiction', 1),
('Rage Against the Machine', 1),
('Tool', 1),
('Nine Inch Nails', 1),
('Daft Punk', 1),
('The Chemical Brothers', 1),
('Massive Attack', 1),
('Portishead', 1),
('Björk', 1),
('PJ Harvey', 1),
('Nick Cave & The Bad Seeds', 1),
('Tom Waits', 1),
('Leonard Cohen', 1),
('Joni Mitchell', 1),
('Neil Young', 1),
('Van Morrison', 1),
('The Kinks', 1),
('The Who', 1),
('Cream', 1),
('Eric Clapton', 1),
('Jeff Beck', 1),
('Santana', 1),
('Grateful Dead', 1),
('Jefferson Airplane', 1),
('Janis Joplin', 1),
('Big Brother and the Holding Company', 1),
('Creedence Clearwater Revival', 1),
('The Band', 1),
('The Byrds', 1),
('Buffalo Springfield', 1),
('Crosby, Stills, Nash & Young', 1),
('Eagles', 1),
('America', 1),
('Jackson Browne', 1),
('James Taylor', 1),
('Carole King', 1),
('Billy Joel', 1),
('Steely Dan', 1),
('Supertramp', 1),
('Genesis', 1),
('Yes', 1),
('Emerson, Lake & Palmer', 1),
('King Crimson', 1),
('Jethro Tull', 1),
('Rush', 1),
('Iron Maiden', 1),
('Judas Priest', 1),
('Motörhead', 1),
('Slayer', 1),
('Megadeth', 1),
('Anthrax', 1),
('Pantera', 1),
('Sepultura', 1),
('Black Flag', 1),
('Dead Kennedys', 1),
('Minor Threat', 1),
('Fugazi', 1),
('Bad Religion', 1),
('NOFX', 1),
('The Offspring', 1),
('Green Day', 1),
('Blink-182', 1),
('Sum 41', 1),
('My Chemical Romance', 1),
('Fall Out Boy', 1),
('Paramore', 1),
('The Killers', 1),
('Franz Ferdinand', 1),
('Interpol', 1),
('Yeah Yeah Yeahs', 1),
('TV on the Radio', 1),
('Arcade Fire', 1),
('Vampire Weekend', 1),
('MGMT', 1),
('Tame Impala', 1),
('Fleet Foxes', 1),
('Bon Iver', 1),
('Sufjan Stevens', 1),
('Wilco', 1),
('Pavement', 1),
('Guided by Voices', 1),
('Built to Spill', 1),
('Dinosaur Jr.', 1),
('My Bloody Valentine', 1),
('Ride', 1),
('Slowdive', 1),
('Cocteau Twins', 1),
('This Mortal Coil', 1),
('Dead Can Dance', 1),
('Siouxsie and the Banshees', 1),
('Bauhaus', 1),
('The Sisters of Mercy', 1),
('The Mission', 1),
('Fields of the Nephilim', 1),
('Echo & the Bunnymen', 1),
('Tears for Fears', 1),
('Simple Minds', 1),
('Duran Duran', 1),
('Spandau Ballet', 1),
('Culture Club', 1),
('Wham!', 1),
('George Michael', 1),
('Eurythmics', 1),
('The Pretenders', 1),
('Pat Benatar', 1),
('Joan Jett & the Blackhearts', 1),
('Heart', 1),
('Stevie Nicks', 1),
('Tom Petty and the Heartbreakers', 1),
('Lynyrd Skynyrd', 1),
('The Allman Brothers Band', 1),
('ZZ Top', 1),
('Aerosmith', 1),
('Van Halen', 1),
('Def Leppard', 1),
('Bon Jovi', 1),
('Guns N'' Roses', 1),
('Mötley Crüe', 1),
('Poison', 1),
('Skid Row', 1),
('Whitesnake', 1),
('Scorpions', 1),
('Accept', 1),
('Rammstein', 1),
('The Prodigy', 1),
('Underworld', 1),
('Orbital', 1),
('Aphex Twin', 1),
('Autechre', 1),
('Boards of Canada', 1),
('Muse', 1),
('Coldplay', 1),
('Sigur Rós', 1),
('Mogwai', 1),
('Explosions in the Sky', 1),
('Godspeed You! Black Emperor', 1),
('Slint', 1),
('Tortoise', 1),
('The Mars Volta', 1),
('At the Drive-In', 1),
('System of a Down', 1),
('Deftones', 1),
('Korn', 1),
('Linkin Park', 1),
('Evanescence', 1),
('Within Temptation', 1),
('Nightwish', 1),
('Epica', 1)
ON CONFLICT (artist_name) DO NOTHING;
