import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const STYLE_CONFIG: Record<string, { label: string; emoji: string }> = {
  vector: { label: "Vector Illustration", emoji: "🎨" },
  watercolor: { label: "Watercolor Paint", emoji: "💧" },
  retro: { label: "Retro Style", emoji: "🕹️" },
  neon: { label: "Neon Glow", emoji: "💡" },
  minimalist: { label: "Minimalist Line", emoji: "✏️" },
  popart: { label: "Pop Art", emoji: "💥" },
  metallic: { label: "Metallic Shine", emoji: "✨" }
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const { baseDesignUrl, buttonId } = await req.json();

    if (!baseDesignUrl || !buttonId) {
      throw new Error('baseDesignUrl and buttonId are required');
    }

    console.log('🎨 Starting button style generation:', { buttonId, baseDesignUrl });

    const styleVariants = [];
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');

    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    // Download base design
    const baseImageResponse = await fetch(baseDesignUrl);
    if (!baseImageResponse.ok) {
      throw new Error(`Failed to fetch base design: ${baseImageResponse.statusText}`);
    }
    const baseImageBlob = await baseImageResponse.blob();
    const baseImageBuffer = await baseImageBlob.arrayBuffer();
    
    // Convert to base64 without stack overflow
    const bytes = new Uint8Array(baseImageBuffer);
    let binary = '';
    const chunkSize = 8192;
    for (let i = 0; i < bytes.length; i += chunkSize) {
      const chunk = bytes.subarray(i, Math.min(i + chunkSize, bytes.length));
      binary += String.fromCharCode.apply(null, Array.from(chunk));
    }
    const baseImageBase64 = btoa(binary);

    for (const [styleKey, { label, emoji }] of Object.entries(STYLE_CONFIG)) {
      console.log(`🎨 Generating ${label} style...`);

      try {
        const prompt = getStylePrompt(styleKey, label);

        const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${LOVABLE_API_KEY}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            model: 'google/gemini-2.5-flash-image-preview',
            messages: [
              {
                role: 'user',
                content: [
                  { type: 'text', text: prompt },
                  {
                    type: 'image_url',
                    image_url: { url: `data:image/png;base64,${baseImageBase64}` }
                  }
                ]
              }
            ],
            modalities: ['image', 'text']
          })
        });

        if (!aiResponse.ok) {
          const errorText = await aiResponse.text();
          console.error(`AI API error for ${styleKey}:`, errorText);
          throw new Error(`AI API returned ${aiResponse.status}: ${errorText}`);
        }

        const aiData = await aiResponse.json();
        const generatedImageUrl = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;

        if (!generatedImageUrl) {
          throw new Error('No image generated by AI');
        }

        // Extract base64 and upload to storage
        const base64Data = generatedImageUrl.replace(/^data:image\/\w+;base64,/, '');
        const imageBuffer = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

        const fileName = `button-${buttonId}-${styleKey}-${Date.now()}.png`;
        const { data: uploadData, error: uploadError } = await supabase.storage
          .from('time-machine-posters')
          .upload(fileName, imageBuffer, {
            contentType: 'image/png',
            cacheControl: '31536000'
          });

        if (uploadError) {
          console.error('Storage upload error:', uploadError);
          throw uploadError;
        }

        const { data: { publicUrl } } = supabase.storage
          .from('time-machine-posters')
          .getPublicUrl(fileName);

        styleVariants.push({
          style: styleKey,
          url: publicUrl,
          label,
          emoji
        });

        console.log(`✅ Generated ${label} style: ${publicUrl}`);

      } catch (error) {
        console.error(`Error generating ${label}:`, error);
        // Continue with other styles even if one fails
      }
    }

    console.log(`✅ Generated ${styleVariants.length} button style variants`);

    return new Response(
      JSON.stringify({ styleVariants }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in batch-generate-button-styles:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});

function getStylePrompt(styleKey: string, label: string): string {
  const basePrompt = `Transform this image into a stylized button design. 
CRITICAL: Maintain the EXACT circular shape and composition. Only change the artistic style.
The image must remain a perfect circle suitable for a round button badge.
Style: ${label}`;

  const stylePrompts: Record<string, string> = {
    vector: `${basePrompt}
- Create smooth, clean vector artwork with solid colors
- Use bold outlines and simplified shapes
- Flat color style with slight gradients for depth
- Professional graphic design look`,

    watercolor: `${basePrompt}
- Apply soft watercolor paint effects with gentle blending
- Use flowing, organic color transitions
- Add subtle paper texture
- Dreamy, artistic watercolor aesthetic`,

    retro: `${basePrompt}
- Transform into vintage 80s/90s style
- Use retro color palette (pinks, purples, teals)
- Add slight grain and nostalgic vibe
- Classic retro aesthetic with modern clarity`,

    neon: `${basePrompt}
- Apply bright neon colors with glowing effects
- High contrast with dark background elements
- Electric, vibrant color palette
- Futuristic neon sign aesthetic`,

    minimalist: `${basePrompt}
- Convert to clean line art style
- Simple, essential lines only
- Monochromatic or limited color palette
- Modern minimalist design`,

    popart: `${basePrompt}
- Bold pop art style with high contrast
- Add halftone dots pattern where appropriate
- Bright, saturated comic book colors
- Dynamic, energetic pop art aesthetic`,

    metallic: `${basePrompt}
- Apply shiny metallic effect with reflective surfaces
- Use metallic color palette (silver, gold, chrome)
- Add realistic light reflections and shine
- Premium, polished metallic look`
  };

  return stylePrompts[styleKey] || basePrompt;
}
