import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log('🎵 Starting daily music history generation...');

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    // Get current date
    const now = new Date();
    const dayOfMonth = now.getDate();
    const monthOfYear = now.getMonth() + 1; // 0-indexed
    const eventDate = now.toISOString().split('T')[0]; // YYYY-MM-DD

    // Check if we already have events for today
    const { data: existing } = await supabase
      .from('music_history_events')
      .select('id')
      .eq('event_date', eventDate)
      .maybeSingle();

    if (existing) {
      console.log('✅ Events already exist for today, skipping generation');
      return new Response(
        JSON.stringify({ success: true, message: 'Events already exist for today' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Generate historical events for this day
    const monthNames = ['januari', 'februari', 'maart', 'april', 'mei', 'juni', 
                        'juli', 'augustus', 'september', 'oktober', 'november', 'december'];
    
    const prompt = `Je bent een muziekhistoricus. Genereer een lijst van 3-7 belangrijke muziekgebeurtenissen die plaatsvonden op ${dayOfMonth} ${monthNames[monthOfYear - 1]} in verschillende jaren.

**Belangrijke regels:**
- Elke gebeurtenis moet een ECHT historisch moment zijn uit de muziekgeschiedenis
- Varieer de jaren (spreiding van vroege jaren tot recente geschiedenis)
- Mix verschillende gebeurtenistypes: album releases, concerten, mijlpalen, overlijdens, geboortes van artiesten
- Focus op verschillende genres: rock, pop, jazz, soul, electronic, etc.
- Gebruik een mix van bekende en minder bekende maar belangrijke momenten
- Wees specifiek en accuraat met jaartallen en details

Retourneer een JSON array met gebeurtenissen in dit formaat:
[
  {
    "year": 1969,
    "title": "The Beatles geven hun laatste openbare optreden",
    "description": "Op het dak van Apple Corps in Londen verzorgden The Beatles hun legendarische rooftop concert, hun laatste publieke optreden als band. De politie moest de gebeurtenis uiteindelijk beëindigen na klachten van omwonenden.",
    "category": "concert"
  }
]

Mogelijke categorieën: "release", "concert", "milestone", "birth", "death", "event"

Geef ALLEEN de JSON array terug, geen andere tekst.`;

    console.log('🤖 Calling AI to generate music history events...');

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          {
            role: 'system',
            content: 'Je bent een expert muziekhistoricus. Je genereert nauwkeurige, geverifieerde muziekgeschiedenis events. Retourneer alleen valid JSON arrays.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7
      })
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI API error:', aiResponse.status, errorText);
      
      if (aiResponse.status === 402) {
        return new Response(
          JSON.stringify({ 
            error: 'Onvoldoende Lovable AI credits. Voeg credits toe in Settings → Workspace → Usage.',
            errorType: 'INSUFFICIENT_CREDITS',
            success: false 
          }),
          { status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      throw new Error(`AI generation failed: ${aiResponse.status} ${errorText}`);
    }

    const aiData = await aiResponse.json();
    const content = aiData.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error('No content generated by AI');
    }

    console.log('📝 AI response received, parsing events...');

    // Parse JSON from response (handle potential markdown code blocks)
    let events;
    try {
      const jsonMatch = content.match(/\[[\s\S]*\]/);
      if (jsonMatch) {
        events = JSON.parse(jsonMatch[0]);
      } else {
        events = JSON.parse(content);
      }
    } catch (parseError) {
      console.error('Failed to parse AI response as JSON:', content);
      throw new Error('Invalid JSON response from AI');
    }

    if (!Array.isArray(events) || events.length === 0) {
      throw new Error('AI did not return a valid events array');
    }

    // Sort events by year (oldest to newest)
    events.sort((a, b) => a.year - b.year);

    console.log(`✅ Generated ${events.length} music history events`);

    // Save to database
    const { data, error: dbError } = await supabase
      .from('music_history_events')
      .insert({
        event_date: eventDate,
        day_of_month: dayOfMonth,
        month_of_year: monthOfYear,
        events: events
      })
      .select()
      .single();

    if (dbError) {
      console.error('Database error:', dbError);
      throw dbError;
    }

    console.log('💾 Events saved to database:', data.id);

    return new Response(
      JSON.stringify({
        success: true,
        event_date: eventDate,
        events_count: events.length,
        events: events
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('❌ Error in generate-daily-music-history:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Unknown error',
        success: false 
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 500
      }
    );
  }
});
