import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.52.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

const openAIApiKey = Deno.env.get('OPENAI_API_KEY');
const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

const supabase = createClient(supabaseUrl, supabaseServiceKey);

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log('Starting weekly forum discussion generation...');
    
    // Get a random artist from the database
    const { data: randomAlbum, error: albumError } = await supabase
      .from('unified_scans')
      .select('artist, title, discogs_id')
      .not('artist', 'is', null)
      .not('title', 'is', null)
      .limit(1)
      .order('created_at', { ascending: false });

    if (albumError) {
      console.error('Error fetching random album:', albumError);
      throw albumError;
    }

    const album = randomAlbum?.[0];
    if (!album) {
      console.log('No albums found in database');
      throw new Error('No albums found in database');
    }

    console.log(`Selected album: ${album.artist} - ${album.title}`);

    // Generate discussion content using OpenAI
    const discussionPrompt = `
    Je bent een muziekexpert die elke week een interessante discussie start over een album voor een Nederlandse muziekforum. 
    
    Album: "${album.title}" door ${album.artist}
    
    Creëer een boeiende discussie met:
    1. Een korte, pakkende titel (max 80 karakters)
    2. Een interessante beschrijving die mensen uitnodigt om te reageren (max 300 woorden)
    
    De beschrijving moet:
    - Interessante achtergrondinformatie bevatten
    - Specifieke vragen stellen die discussie uitlokken
    - Warm en uitnodigend zijn
    - In het Nederlands geschreven zijn
    - Persoonlijke ervaringen en herinneringen aanmoedigen
    
    Retourneer je antwoord in JSON format:
    {
      "title": "discussie titel",
      "description": "volledige beschrijving"
    }
    `;

    const openAIResponse = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openAIApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        messages: [
          { role: 'system', content: 'Je bent een ervaren muziekjournalist die boeiende discussies creëert voor een Nederlandse muziekforum.' },
          { role: 'user', content: discussionPrompt }
        ],
        max_tokens: 800,
        temperature: 0.8,
      }),
    });

    const openAIData = await openAIResponse.json();
    
    if (!openAIData.choices?.[0]?.message?.content) {
      throw new Error('No content generated by OpenAI');
    }

    const generatedContent = JSON.parse(openAIData.choices[0].message.content);
    console.log('Generated discussion content:', generatedContent);

    // Create the forum topic
    const { data: newTopic, error: topicError } = await supabase
      .from('forum_topics')
      .insert({
        title: generatedContent.title,
        description: generatedContent.description,
        topic_type: 'auto_generated',
        artist_name: album.artist,
        album_title: album.title,
        is_featured: true,
        created_by: '00000000-0000-0000-0000-000000000000', // System user
      })
      .select()
      .single();

    if (topicError) {
      console.error('Error creating forum topic:', topicError);
      throw topicError;
    }

    console.log('Created new weekly discussion:', newTopic);

    // Mark previous auto-generated topics as not featured
    await supabase
      .from('forum_topics')
      .update({ is_featured: false })
      .eq('topic_type', 'auto_generated')
      .neq('id', newTopic.id);

    return new Response(
      JSON.stringify({
        success: true,
        message: 'Weekly forum discussion created successfully',
        topic: newTopic,
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );

  } catch (error) {
    console.error('Error in weekly-forum-discussions function:', error);
    
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message,
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    );
  }
});