import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

function generateSlug(artist: string, song: string): string {
  const base = `${artist}-${song}-christmas-socks`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return base.substring(0, 80);
}

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const { artistName, songTitle, artistImageUrl } = await req.json();

    if (!artistName || !songTitle) {
      return new Response(
        JSON.stringify({ error: 'artistName and songTitle are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('🧦🎄 Generating artist Christmas sock for:', artistName, '-', songTitle);
    const startTime = Date.now();

    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY not configured');
    }

    // Build the prompt for artist portrait Christmas sock
    const prompt = `Create premium BLACK crew socks featuring a festive Christmas portrait design.

**THE ARTIST:** ${artistName}
**THE SONG:** "${songTitle}"

**CRITICAL DESIGN REQUIREMENTS:**
- Base: Premium BLACK crew socks (crew neck length)
- Design: Festive Christmas portrait of ${artistName} in pop art posterized style
- The artist should be recognizable but artistically stylized
- Christmas atmosphere: snow, holly, red/green/gold accents, winter vibes
- Bold pop art colors with high contrast
- NOT just a face photo - creative artistic interpretation

**COMPOSITION:**
- Show 2 black socks side by side, standing upright
- 3D perspective showing natural sock form with subtle fabric draping
- Professional product photography with clean studio lighting
- Design panel clearly visible on the front-facing side of each sock
- Natural shadows and depth to show dimensionality

**STYLE:**
- Pop art posterized aesthetic with bold graphic elements
- Christmas/winter themed color palette (red, green, gold, white)
- Festive holiday atmosphere
- Premium streetwear aesthetic
- Clean white background
- Ultra high resolution

**INSPIRATION:**
Think iconic Christmas imagery - ${artistName} in their most memorable Christmas look, surrounded by festive elements like snowflakes, holly, ornaments, or winter scenes. The result should feel like collector's edition Christmas merchandise.`;

    console.log('🎨 Calling AI for artist Christmas sock design...');

    // Build the request - with or without reference image
    const messageContent: any[] = [{ type: 'text', text: prompt }];
    
    if (artistImageUrl) {
      console.log('📸 Using artist reference image:', artistImageUrl.substring(0, 60) + '...');
      messageContent.push({
        type: 'image_url',
        image_url: { url: artistImageUrl }
      });
    }

    const aiResponse = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash-image-preview',
        messages: [{ role: 'user', content: messageContent }],
        modalities: ['image', 'text']
      })
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error('AI API Error:', aiResponse.status, errorText);
      throw new Error(`AI API returned ${aiResponse.status}`);
    }

    const aiData = await aiResponse.json();
    const imageUrl = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!imageUrl) {
      throw new Error('No image generated by AI');
    }

    console.log('✅ Artist Christmas sock design generated, uploading to storage...');

    // Upload to Supabase Storage
    const base64Data = imageUrl.replace(/^data:image\/\w+;base64,/, '');
    const imageBlob = Uint8Array.from(atob(base64Data), c => c.charCodeAt(0));

    const timestamp = Date.now();
    const baseSlug = generateSlug(artistName, songTitle);
    const slug = `${baseSlug}-${timestamp}`;
    const filename = `christmas/${slug}.png`;

    const { error: uploadError } = await supabase.storage
      .from('time-machine-posters')
      .upload(`socks/${filename}`, imageBlob, {
        contentType: 'image/png',
        upsert: false
      });

    if (uploadError) {
      console.error('Upload error:', uploadError);
      throw new Error(`Failed to upload: ${uploadError.message}`);
    }

    const { data: { publicUrl } } = supabase.storage
      .from('time-machine-posters')
      .getPublicUrl(`socks/${filename}`);

    console.log('📦 Creating album_socks record...');

    // Christmas color palette
    const christmasPalette = {
      primary_color: '#C41E3A',
      secondary_color: '#228B22',
      accent_color: '#FFD700',
    };

    // Create album_socks record
    const { data: sockData, error: sockError } = await supabase
      .from('album_socks')
      .insert({
        artist_name: artistName,
        album_title: songTitle,
        album_cover_url: artistImageUrl || publicUrl,
        primary_color: christmasPalette.primary_color,
        secondary_color: christmasPalette.secondary_color,
        accent_color: christmasPalette.accent_color,
        color_palette: ['#C41E3A', '#228B22', '#FFD700', '#FFFFFF'],
        design_theme: 'posterize',
        pattern_type: 'christmas',
        base_design_url: publicUrl,
        slug: slug,
        genre: 'Christmas',
        generation_time_ms: Date.now() - startTime,
        description: `Feestelijke kerstsokken met ${artistName} in pop art stijl. Geïnspireerd door de klassieker "${songTitle}".`,
        story_text: `Deze unieke kerstsokken vieren ${artistName}'s iconische kersthit "${songTitle}". Het artistieke portret in pop art stijl met feestelijke kerstelementen maakt deze sokken tot een must-have voor elke muziekliefhebber.`
      })
      .select()
      .single();

    if (sockError) {
      console.error('Database error:', sockError);
      throw new Error(`Failed to save sock: ${sockError.message}`);
    }

    const generationTime = Date.now() - startTime;
    console.log(`🎉 Artist Christmas sock complete in ${generationTime}ms`);
    console.log(`   Sock ID: ${sockData.id}`);
    console.log(`   Design URL: ${publicUrl}`);

    return new Response(
      JSON.stringify({
        success: true,
        sock_id: sockData.id,
        slug: sockData.slug,
        base_design_url: publicUrl,
        artist: artistName,
        song: songTitle,
        generation_time_ms: generationTime
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
    );

  } catch (error) {
    console.error('❌ Error generating artist Christmas sock:', error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : 'Unknown error',
        success: false 
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    );
  }
});
