-- Update unified_scans view to include artwork_url
CREATE OR REPLACE VIEW unified_scans AS
SELECT ai_scan_results.id,
    ai_scan_results.created_at,
    ai_scan_results.updated_at,
    ai_scan_results.user_id,
    ai_scan_results.artist,
    ai_scan_results.title,
    ai_scan_results.label,
    ai_scan_results.catalog_number,
    ai_scan_results.discogs_id,
    ai_scan_results.discogs_url,
    ai_scan_results.condition_grade,
    'ai_scan_results'::text AS source_table,
    ai_scan_results.media_type,
    ai_scan_results.photo_urls,
    ai_scan_results.status,
    ai_scan_results.error_message,
    ai_scan_results.confidence_score,
    ai_scan_results.ai_description,
    ai_scan_results.search_queries,
    ai_scan_results.genre,
    ai_scan_results.country,
    ai_scan_results.format,
    ai_scan_results.style,
    ai_scan_results.barcode,
    ai_scan_results.matrix_number,
    ai_scan_results.comments,
    ai_scan_results.year,
    ai_scan_results.is_flagged_incorrect,
    NULL::numeric AS calculated_advice_price,
    NULL::numeric AS lowest_price,
    NULL::numeric AS median_price,
    NULL::numeric AS highest_price,
    NULL::boolean AS is_public,
    NULL::boolean AS is_for_sale,
    NULL::uuid AS release_id,
    ai_scan_results.artwork_url
   FROM ai_scan_results
UNION ALL
 SELECT cd_scan.id,
    cd_scan.created_at,
    cd_scan.updated_at,
    cd_scan.user_id,
    cd_scan.artist,
    cd_scan.title,
    cd_scan.label,
    cd_scan.catalog_number,
    cd_scan.discogs_id,
    cd_scan.discogs_url,
    cd_scan.condition_grade,
    'cd_scan'::text AS source_table,
    'cd'::text AS media_type,
    ARRAY[cd_scan.front_image, cd_scan.back_image, cd_scan.barcode_image] AS photo_urls,
        CASE
            WHEN cd_scan.calculated_advice_price IS NOT NULL THEN 'completed'::text
            ELSE 'pending'::text
        END AS status,
    NULL::text AS error_message,
    NULL::numeric AS confidence_score,
    NULL::text AS ai_description,
    NULL::text[] AS search_queries,
    cd_scan.genre,
    cd_scan.country,
    cd_scan.format,
    cd_scan.style,
    cd_scan.barcode_number AS barcode,
    cd_scan.matrix_number,
    NULL::text AS comments,
    cd_scan.year,
    NULL::boolean AS is_flagged_incorrect,
    cd_scan.calculated_advice_price,
    cd_scan.lowest_price,
    cd_scan.median_price,
    cd_scan.highest_price,
    cd_scan.is_public,
    cd_scan.is_for_sale,
    cd_scan.release_id,
    NULL::text AS artwork_url
   FROM cd_scan
UNION ALL
 SELECT vinyl2_scan.id,
    vinyl2_scan.created_at,
    vinyl2_scan.updated_at,
    vinyl2_scan.user_id,
    vinyl2_scan.artist,
    vinyl2_scan.title,
    vinyl2_scan.label,
    vinyl2_scan.catalog_number,
    vinyl2_scan.discogs_id,
    vinyl2_scan.discogs_url,
    vinyl2_scan.condition_grade,
    'vinyl2_scan'::text AS source_table,
    'vinyl'::text AS media_type,
    ARRAY[vinyl2_scan.catalog_image, vinyl2_scan.matrix_image, vinyl2_scan.additional_image] AS photo_urls,
        CASE
            WHEN vinyl2_scan.calculated_advice_price IS NOT NULL THEN 'completed'::text
            ELSE 'pending'::text
        END AS status,
    NULL::text AS error_message,
    NULL::numeric AS confidence_score,
    NULL::text AS ai_description,
    NULL::text[] AS search_queries,
    vinyl2_scan.genre,
    vinyl2_scan.country,
    vinyl2_scan.format,
    vinyl2_scan.style,
    NULL::text AS barcode,
    vinyl2_scan.matrix_number,
    NULL::text AS comments,
    vinyl2_scan.year,
    NULL::boolean AS is_flagged_incorrect,
    vinyl2_scan.calculated_advice_price,
    vinyl2_scan.lowest_price,
    vinyl2_scan.median_price,
    vinyl2_scan.highest_price,
    vinyl2_scan.is_public,
    vinyl2_scan.is_for_sale,
    vinyl2_scan.release_id,
    NULL::text AS artwork_url
   FROM vinyl2_scan;