-- Voeg 200+ nieuwe artiesten toe aan curated_artists
-- Focus op: Nederlandse, Franse, Dance/House, en internationale klassiekers

INSERT INTO curated_artists (artist_name, priority, country_code) VALUES
-- NEDERLANDSE ARTIESTEN (50+)
('André Hazes', 1, 'NL'),
('Guus Meeuwis', 1, 'NL'),
('Marco Borsato', 1, 'NL'),
('Bløf', 1, 'NL'),
('Di-rect', 1, 'NL'),
('Anouk', 1, 'NL'),
('Doe Maar', 1, 'NL'),
('Golden Earring', 1, 'NL'),
('Shocking Blue', 1, 'NL'),
('Focus', 1, 'NL'),
('Kensington', 1, 'NL'),
('Chef''Special', 1, 'NL'),
('Krezip', 1, 'NL'),
('Kane', 1, 'NL'),
('3JS', 1, 'NL'),
('Nick & Simon', 1, 'NL'),
('Nielson', 1, 'NL'),
('Suzan & Freek', 1, 'NL'),
('Davina Michelle', 1, 'NL'),
('Snelle', 1, 'NL'),
('Lil'' Kleine', 1, 'NL'),
('Boef', 1, 'NL'),
('Ronnie Flex', 1, 'NL'),
('Sevn Alias', 1, 'NL'),
('Frenna', 1, 'NL'),
('Josylvio', 1, 'NL'),
('Broederliefde', 1, 'NL'),
('De Jeugd van Tegenwoordig', 1, 'NL'),
('Opgezwoansen', 1, 'NL'),
('René Froger', 1, 'NL'),
('Gerard Joling', 1, 'NL'),
('Tino Martin', 1, 'NL'),
('Wolter Kroes', 1, 'NL'),
('Frans Bauer', 1, 'NL'),
('Jan Smit', 1, 'NL'),
('Jannes', 1, 'NL'),
('Hazes Jr', 1, 'NL'),
('Henk Westbroek', 1, 'NL'),
('Acda en de Munnik', 1, 'NL'),
('Spinvis', 1, 'NL'),
('Douwe Bob', 1, 'NL'),
('Duncan Laurence', 1, 'NL'),
('S10', 1, 'NL'),
('Maan', 1, 'NL'),
('Davina Michelle', 1, 'NL'),
('Emma Heesters', 1, 'NL'),
('Rolf Sanchez', 1, 'NL'),
('Danny Vera', 1, 'NL'),
('Waylon', 1, 'NL'),
('Ilse DeLange', 1, 'NL'),
('The Common Linnets', 1, 'NL'),

-- FRANSE ARTIESTEN (50+)
('Édith Piaf', 1, 'FR'),
('Charles Aznavour', 1, 'FR'),
('Jacques Brel', 1, 'BE'),
('Serge Gainsbourg', 1, 'FR'),
('France Gall', 1, 'FR'),
('Françoise Hardy', 1, 'FR'),
('Johnny Hallyday', 1, 'FR'),
('Michel Sardou', 1, 'FR'),
('Jean-Jacques Goldman', 1, 'FR'),
('Céline Dion', 1, 'CA'),
('Stromae', 1, 'BE'),
('Angèle', 1, 'BE'),
('Christine and the Queens', 1, 'FR'),
('Aya Nakamura', 1, 'FR'),
('Zaz', 1, 'FR'),
('Indochine', 1, 'FR'),
('Téléphone', 1, 'FR'),
('Mylène Farmer', 1, 'FR'),
('Patrick Bruel', 1, 'FR'),
('Francis Cabrel', 1, 'FR'),
('Michel Polnareff', 1, 'FR'),
('Alain Souchon', 1, 'FR'),
('Laurent Voulzy', 1, 'FR'),
('Vanessa Paradis', 1, 'FR'),
('Véronique Sanson', 1, 'FR'),
('Michel Berger', 1, 'FR'),
('Daniel Balavoine', 1, 'FR'),
('Renaud', 1, 'FR'),
('Claude François', 1, 'FR'),
('Charles Trenet', 1, 'FR'),
('Yves Montand', 1, 'FR'),
('Georges Brassens', 1, 'FR'),
('Léo Ferré', 1, 'FR'),
('MC Solaar', 1, 'FR'),
('IAM', 1, 'FR'),
('NTM', 1, 'FR'),
('PNL', 1, 'FR'),
('Booba', 1, 'FR'),
('Ninho', 1, 'FR'),
('Jul', 1, 'FR'),
('Orelsan', 1, 'FR'),
('Nekfeu', 1, 'FR'),
('Damso', 1, 'BE'),
('Soprano', 1, 'FR'),
('Maître Gims', 1, 'FR'),
('Kendji Girac', 1, 'FR'),
('Vianney', 1, 'FR'),
('Julien Doré', 1, 'FR'),
('Phoenix', 1, 'FR'),
('Air', 1, 'FR'),
('M83', 1, 'FR'),

-- DANCE/HOUSE/EDM ARTIESTEN (50+)
('Tiësto', 1, 'NL'),
('Martin Garrix', 1, 'NL'),
('Afrojack', 1, 'NL'),
('Armin van Buuren', 1, 'NL'),
('Hardwell', 1, 'NL'),
('Don Diablo', 1, 'NL'),
('Nicky Romero', 1, 'NL'),
('Oliver Heldens', 1, 'NL'),
('R3HAB', 1, 'NL'),
('Fedde Le Grand', 1, 'NL'),
('Sander van Doorn', 1, 'NL'),
('Showtek', 1, 'NL'),
('Yellow Claw', 1, 'NL'),
('Brennan Heart', 1, 'NL'),
('Headhunterz', 1, 'NL'),
('Angerfist', 1, 'NL'),
('Wildstylez', 1, 'NL'),
('Noisecontrollers', 1, 'NL'),
('Sunnery James & Ryan Marciano', 1, 'NL'),
('Lucas & Steve', 1, 'NL'),
('Quintino', 1, 'NL'),
('Laidback Luke', 1, 'NL'),
('Ferry Corsten', 1, 'NL'),
('Cosmic Gate', 1, 'DE'),
('Paul van Dyk', 1, 'DE'),
('ATB', 1, 'DE'),
('Scooter', 1, 'DE'),
('David Guetta', 1, 'FR'),
('Avicii', 1, 'SE'),
('Swedish House Mafia', 1, 'SE'),
('Deadmau5', 1, 'CA'),
('Marshmello', 1, 'US'),
('Kygo', 1, 'NO'),
('Calvin Harris', 1, 'GB'),
('Diplo', 1, 'US'),
('Skrillex', 1, 'US'),
('Major Lazer', 1, 'US'),
('The Chainsmokers', 1, 'US'),
('Zedd', 1, 'DE'),
('Robin Schulz', 1, 'DE'),
('DJ Snake', 1, 'FR'),
('Kungs', 1, 'FR'),
('Ofenbach', 1, 'FR'),
('Bob Sinclar', 1, 'FR'),
('Petit Biscuit', 1, 'FR'),
('Duke Dumont', 1, 'GB'),
('Disclosure', 1, 'GB'),
('Rudimental', 1, 'GB'),
('Sigma', 1, 'GB'),
('Clean Bandit', 1, 'GB'),

-- AANVULLENDE INTERNATIONALE KLASSIEKERS (50+)
('ABBA', 1, 'SE'),
('The Bee Gees', 1, 'AU'),
('Donna Summer', 1, 'US'),
('Gloria Gaynor', 1, 'US'),
('KC and the Sunshine Band', 1, 'US'),
('Earth, Wind & Fire', 1, 'US'),
('Chic', 1, 'US'),
('Kool & The Gang', 1, 'US'),
('The Commodores', 1, 'US'),
('Diana Ross', 1, 'US'),
('The Jackson 5', 1, 'US'),
('Smokey Robinson', 1, 'US'),
('The Temptations', 1, 'US'),
('The Four Tops', 1, 'US'),
('Gladys Knight & the Pips', 1, 'US'),
('Barry White', 1, 'US'),
('Al Green', 1, 'US'),
('Otis Redding', 1, 'US'),
('Sam Cooke', 1, 'US'),
('Ray Charles', 1, 'US'),
('Nat King Cole', 1, 'US'),
('Frank Sinatra', 1, 'US'),
('Dean Martin', 1, 'US'),
('Sammy Davis Jr.', 1, 'US'),
('Tony Bennett', 1, 'US'),
('Ella Fitzgerald', 1, 'US'),
('Louis Armstrong', 1, 'US'),
('Duke Ellington', 1, 'US'),
('Miles Davis', 1, 'US'),
('John Coltrane', 1, 'US'),
('Herbie Hancock', 1, 'US'),
('Quincy Jones', 1, 'US'),
('George Benson', 1, 'US'),
('Sade', 1, 'GB'),
('Simply Red', 1, 'GB'),
('Phil Collins', 1, 'GB'),
('Peter Gabriel', 1, 'GB'),
('Kate Bush', 1, 'GB'),
('Elton John', 1, 'GB'),
('Queen', 1, 'GB'),
('David Bowie', 1, 'GB'),
('The Police', 1, 'GB'),
('Dire Straits', 1, 'GB'),
('Bryan Adams', 1, 'CA'),
('Bon Iver', 1, 'US'),
('Fleet Foxes', 1, 'US'),
('The National', 1, 'US'),
('Arcade Fire', 1, 'CA'),
('The xx', 1, 'GB'),
('Glass Animals', 1, 'GB'),
('Alt-J', 1, 'GB'),
('Mumford & Sons', 1, 'GB'),
('Hozier', 1, 'IE'),
('Lewis Capaldi', 1, 'GB'),
('Ed Sheeran', 1, 'GB'),
('Adele', 1, 'GB'),
('Amy Winehouse', 1, 'GB'),
('Sam Smith', 1, 'GB'),
('Dua Lipa', 1, 'GB'),
('Harry Styles', 1, 'GB')
ON CONFLICT (artist_name) DO NOTHING;