// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtqepclpqgtamhzgwyva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0cWVwY2xwcWd0YW1oemd3eXZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTc5OTMsImV4cCI6MjA2NzM5Mzk5M30.N709EYV5cs3yCmnHIS9POg4ShwpUORLy7m0nsFM9RZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});